apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cups-client.fullname" . }}
  labels:
    {{- include "cups-client.labels" . | nindent 4 }}
    app: {{ include "cups-client.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cups-client.selectorLabels" . | nindent 6 }}
      app: {{ include "cups-client.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cups-client.selectorLabels" . | nindent 8 }}
        app: {{ include "cups-client.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cups-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: client-conf
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["sh", "-c", "cp /tmp/client.conf /etc/cups/client.conf && chmod 0660 /etc/cups/client.conf && chown 1000:7 /etc/cups/client.conf"]
          volumeMounts:
            - name: client-conf
              mountPath: /tmp/client.conf
              subPath: client.conf
            - name: empty
              mountPath: /etc/cups/
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts: 
            - name: empty
              mountPath: /etc/cups/client.conf
              subPath: client.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes: 
        - name: client-conf
          configMap:
            name: {{ include "cups-client.fullname" . }}-conf
            defaultMode: 0777
        - name: empty
          emptyDir: {}

