{{- range .Values.statefulSets }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cups.fullname" $ }}-{{ .name }}
  labels: 
    {{- include "cups.labels" $ | nindent 4 }}
    app: {{ include "cups.fullname" $ }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  serviceName: {{ include "cups.fullname" $  }}
  selector:
    matchLabels: 
      app: {{ include "cups.fullname" $ }}
      # label unique to the statefulset
      statefulset: {{ .name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "cups.fullname" $ }}
        statefulset: {{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cups.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: cupsd-conf
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["sh", "-c", "cp /tmp/cupsd.conf /etc/cups/cupsd.conf && chmod 0660 /etc/cups/cupsd.conf && chown 1000:7 /etc/cups/cupsd.conf && cp /tmp/printers.conf /etc/cups/printers.conf && chmod 0660 /etc/cups/printers.conf && chown 1000:7 /etc/cups/printers.conf"]
          volumeMounts:
            - name: cupsd-conf
              mountPath: /tmp/cupsd.conf
              subPath: cupsd.conf
            - name: cupsd-conf
              mountPath: /tmp/printers.conf
              subPath: printers.conf
            - name: empty
              mountPath: /etc/cups/
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: empty
              mountPath: /etc/cups/cupsd.conf
              subPath: cupsd.conf
            - name: empty
              mountPath: /etc/cups/printers.conf
              subPath: printers.conf
            - name: print-jobs
              mountPath: /var/spool/cups
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values:
                - {{ $.Chart.Name }}
            topologyKey: kubernetes.io/hostname
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cupsd-conf
          configMap:
            name: {{ include "cups.fullname" $ }}-conf
            defaultMode: 0777
        - name: empty
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: print-jobs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClassName }}
      resources: 
        requests: 
          storage: 1Gi

...
{{- end }}